"""
PDF Smart Config Resolver
─────────────────────────
Helper utilities untuk Smart PDF Configuration (Phase 23).

Tugas:
- Memuat config preset dari MongoDB (`pdf_export_configs`).
- Mengisi default values untuk field advanced bila preset belum punya
  (backward-compat dengan preset lama yang hanya berisi `columns`).
- Helper format angka, tanggal, mata uang per language.
- Helper translator label (id/en) dengan custom override.
- Helper section visibility check.

Dipakai oleh:
- `utils/lkp_pdf.py`               — LKP (Lembar Kerja Produksi)
- `routes/rahaza_payroll.py`       — Slip Gaji (Payslip)
- `utils/shift_report_pdf.py`      — Laporan Shift / Handover
- `routes/pdf_smart_config.py`     — Live Preview & metadata
"""
from __future__ import annotations
from datetime import datetime, date, timezone
from typing import Optional, Any

# ─────────────────────────────────────────────────────────────────
# Type & Section definitions (single source of truth)
# ─────────────────────────────────────────────────────────────────

# Bilingual default labels untuk setiap field/section yang dapat
# dikustomisasi user. Struktur: { key: {"id": "...", "en": "..."} }
DEFAULT_LABELS: dict[str, dict[str, str]] = {
    # ── LKP ──
    "lkp.title":            {"id": "Lembar Kerja Produksi", "en": "Production Work Sheet"},
    "lkp.subtitle":         {"id": "Production Work Sheet", "en": "Production Work Sheet"},
    "lkp.lkp_number":       {"id": "Nomor LKP", "en": "LKP Number"},
    "lkp.version":          {"id": "Versi", "en": "Version"},
    "lkp.print_date":       {"id": "Tanggal Cetak", "en": "Print Date"},
    "lkp.printed_by":       {"id": "Dicetak Oleh", "en": "Printed By"},
    "lkp.section_b":        {"id": "B. Informasi Order & Work Order", "en": "B. Order & Work Order Info"},
    "lkp.section_c":        {"id": "C. Informasi Produk / Style", "en": "C. Product / Style Info"},
    "lkp.section_d":        {"id": "D. Bill of Materials (BOM)", "en": "D. Bill of Materials (BOM)"},
    "lkp.section_e":        {"id": "E. Assignment & Resource", "en": "E. Assignment & Resource"},
    "lkp.section_f":        {"id": "F. Urutan Proses Produksi", "en": "F. Production Process Sequence"},
    "lkp.section_g":        {"id": "G. SOP / Work Instruction", "en": "G. SOP / Work Instruction"},
    "lkp.section_h":        {"id": "H. Quality Control Checkpoints", "en": "H. Quality Control Checkpoints"},
    "lkp.section_i":        {"id": "I. Packing & Finishing Instruction", "en": "I. Packing & Finishing"},
    "lkp.section_j":        {"id": "J. Signature / Approval", "en": "J. Signature / Approval"},
    "lkp.section_k":        {"id": "K. Catatan Khusus & Instruksi Tambahan", "en": "K. Special Notes & Additional Instructions"},
    "lkp.section_l":        {"id": "L. Foto Produksi & QC", "en": "L. Production & QC Photos"},

    # ── Payslip ──
    "payslip.title":              {"id": "SLIP GAJI", "en": "PAYSLIP"},
    "payslip.period":             {"id": "Periode", "en": "Period"},
    "payslip.employee_name":      {"id": "Nama Karyawan", "en": "Employee Name"},
    "payslip.employee_code":      {"id": "Kode", "en": "Code"},
    "payslip.scheme":             {"id": "Skema Gaji", "en": "Pay Scheme"},
    "payslip.days_present":       {"id": "Hadir", "en": "Days Present"},
    "payslip.hours_worked":       {"id": "Jam Kerja", "en": "Hours Worked"},
    "payslip.overtime_hours":     {"id": "Lembur", "en": "Overtime"},
    "payslip.earnings_header":    {"id": "Uraian Pendapatan", "en": "Earnings"},
    "payslip.qty":                {"id": "Qty", "en": "Qty"},
    "payslip.unit":               {"id": "Satuan", "en": "Unit"},
    "payslip.amount":             {"id": "Jumlah", "en": "Amount"},
    "payslip.gross_pay":          {"id": "Total Pendapatan", "en": "Gross Pay"},
    "payslip.deductions_header":  {"id": "Potongan", "en": "Deductions"},
    "payslip.net_pay":            {"id": "GAJI BERSIH", "en": "NET PAY"},
    "payslip.notes":              {"id": "Catatan", "en": "Notes"},
    "payslip.signature_approver": {"id": "Disetujui oleh,", "en": "Approved by,"},
    "payslip.signature_employee": {"id": "Diterima oleh,", "en": "Received by,"},
    "payslip.role_hr":            {"id": "Manager / HRD", "en": "Manager / HR"},
    "payslip.role_employee":      {"id": "Karyawan", "en": "Employee"},
    "payslip.footer":             {"id": "Slip ini dicetak otomatis oleh sistem ERP", "en": "This payslip is auto-generated by the ERP system"},

    # ── Shift Report ──
    "shift.title":           {"id": "Laporan Akhir Shift", "en": "End-of-Shift Report"},
    "shift.shift":           {"id": "Shift", "en": "Shift"},
    "shift.line":            {"id": "Line", "en": "Line"},
    "shift.supervisor":      {"id": "Supervisor", "en": "Supervisor"},
    "shift.handover_to":     {"id": "Diserahkan ke", "en": "Handover To"},
    "shift.summary":         {"id": "Ringkasan", "en": "Summary"},
    "shift.issues":          {"id": "Issue / Kendala", "en": "Issues"},
    "shift.actions":         {"id": "Tindakan", "en": "Actions"},
    "shift.attachments":     {"id": "Lampiran", "en": "Attachments"},
    "shift.signature":       {"id": "Tanda Tangan", "en": "Signature"},
}

# Section definitions per PDF type. UI memakai ini untuk render checkbox toggle.
PDF_SECTION_DEFINITIONS: dict[str, list[dict]] = {
    "lkp": [
        {"key": "section_b", "label_key": "lkp.section_b", "default_on": True,  "required": False},
        {"key": "section_c", "label_key": "lkp.section_c", "default_on": True,  "required": False},
        {"key": "section_d", "label_key": "lkp.section_d", "default_on": True,  "required": False},
        {"key": "section_e", "label_key": "lkp.section_e", "default_on": True,  "required": False},
        {"key": "section_f", "label_key": "lkp.section_f", "default_on": True,  "required": False},
        {"key": "section_g", "label_key": "lkp.section_g", "default_on": True,  "required": False},
        {"key": "section_h", "label_key": "lkp.section_h", "default_on": True,  "required": False},
        {"key": "section_i", "label_key": "lkp.section_i", "default_on": True,  "required": False},
        {"key": "section_j", "label_key": "lkp.section_j", "default_on": True,  "required": False},
        {"key": "section_k", "label_key": "lkp.section_k", "default_on": True,  "required": False},
        {"key": "section_l", "label_key": "lkp.section_l", "default_on": True,  "required": False},
        {"key": "qr_code",   "label_key": "common.qr_code", "default_on": True, "required": False},
    ],
    "payslip": [
        {"key": "company_header",  "label_key": "common.company_header", "default_on": True,  "required": True},
        {"key": "employee_info",   "label_key": "payslip.employee_name", "default_on": True,  "required": True},
        {"key": "earnings",        "label_key": "payslip.earnings_header", "default_on": True, "required": True},
        {"key": "deductions",      "label_key": "payslip.deductions_header", "default_on": True, "required": False},
        {"key": "overtime_row",    "label_key": "payslip.overtime_hours", "default_on": True, "required": False},
        {"key": "net_pay_box",     "label_key": "payslip.net_pay",     "default_on": True,  "required": True},
        {"key": "attendance_bar",  "label_key": "payslip.days_present", "default_on": True, "required": False},
        {"key": "notes",           "label_key": "payslip.notes",       "default_on": True,  "required": False},
        {"key": "signature_block", "label_key": "payslip.signature_approver", "default_on": True, "required": False},
        {"key": "footer_text",     "label_key": "common.footer_text",  "default_on": True,  "required": False},
    ],
    "shift-report": [
        {"key": "header",        "label_key": "common.company_header", "default_on": True, "required": True},
        {"key": "summary",       "label_key": "shift.summary",         "default_on": True, "required": True},
        {"key": "issues",        "label_key": "shift.issues",          "default_on": True, "required": False},
        {"key": "actions",       "label_key": "shift.actions",         "default_on": True, "required": False},
        {"key": "attachments",   "label_key": "shift.attachments",     "default_on": True, "required": False},
        {"key": "signature_block", "label_key": "shift.signature",     "default_on": True, "required": False},
        {"key": "footer_text",   "label_key": "common.footer_text",    "default_on": True, "required": False},
    ],
}

# Custom labels yang dapat diedit user per type (key + default per language)
PDF_CUSTOMIZABLE_LABELS: dict[str, list[str]] = {
    "lkp": [
        "lkp.title", "lkp.subtitle",
        "lkp.section_b", "lkp.section_c", "lkp.section_d", "lkp.section_e",
        "lkp.section_f", "lkp.section_g", "lkp.section_h", "lkp.section_i",
        "lkp.section_j", "lkp.section_k", "lkp.section_l",
    ],
    "payslip": [
        "payslip.title", "payslip.period", "payslip.employee_name", "payslip.employee_code",
        "payslip.scheme", "payslip.days_present", "payslip.hours_worked", "payslip.overtime_hours",
        "payslip.earnings_header", "payslip.qty", "payslip.unit", "payslip.amount",
        "payslip.gross_pay", "payslip.deductions_header", "payslip.net_pay", "payslip.notes",
        "payslip.signature_approver", "payslip.signature_employee",
        "payslip.role_hr", "payslip.role_employee", "payslip.footer",
    ],
    "shift-report": [
        "shift.title", "shift.shift", "shift.line", "shift.supervisor", "shift.handover_to",
        "shift.summary", "shift.issues", "shift.actions", "shift.attachments", "shift.signature",
    ],
}

# Common labels shared across types
DEFAULT_LABELS["common.company_header"] = {"id": "Header Perusahaan", "en": "Company Header"}
DEFAULT_LABELS["common.watermark"]      = {"id": "Watermark", "en": "Watermark"}
DEFAULT_LABELS["common.footer_text"]    = {"id": "Teks Footer", "en": "Footer Text"}
DEFAULT_LABELS["common.qr_code"]        = {"id": "QR Code", "en": "QR Code"}


# ─────────────────────────────────────────────────────────────────
# Default config builder
# ─────────────────────────────────────────────────────────────────
def default_config(pdf_type: str) -> dict:
    """Return baseline config for a PDF type (semua section enabled, branding kosong)."""
    sections = [s["key"] for s in PDF_SECTION_DEFINITIONS.get(pdf_type, []) if s.get("default_on", True)]
    return {
        "pdf_type": pdf_type,
        "sections": sections,
        "header": {
            "line1": "",      # default akan ambil dari company_settings
            "line2": "",
            "show_logo": True,
        },
        "footer": {
            "text": "",
            "show_page_number": True,
            "show_print_meta": True,
        },
        "branding": {
            "logo_object_path": "",
            "watermark_text": "",
            "watermark_opacity": 0.08,
            "primary_color": "",   # hex; default akan pakai warna template
            "accent_color": "",
        },
        "page": {
            "size": "A4" if pdf_type in ("lkp", "shift-report") else "A5",
            "orientation": "portrait",
            "margins": {"top": 18, "bottom": 16, "left": 14, "right": 14},   # mm
        },
        "typography": {
            "font_family": "Helvetica",
            "font_scale": 1.0,
        },
        "format": {
            "currency": "IDR",
            "currency_symbol": "Rp",
            "date_format": "DD/MM/YYYY",
            "number_grouping": ".",
            "decimal_separator": ",",
        },
        "language": "id",
        "custom_labels": {},
    }


def merge_config(stored: Optional[dict], pdf_type: str) -> dict:
    """Merge a stored preset (mungkin parsial / legacy kolom-only) dengan default."""
    base = default_config(pdf_type)
    if not stored:
        return base
    # Top-level deep merge for known nested dicts
    for k in ("header", "footer", "branding", "page", "typography", "format"):
        if isinstance(stored.get(k), dict):
            merged = {**base[k], **stored[k]}
            # nested margins
            if k == "page" and isinstance(stored[k].get("margins"), dict):
                merged["margins"] = {**base["page"]["margins"], **stored[k]["margins"]}
            base[k] = merged
    if isinstance(stored.get("sections"), list):
        base["sections"] = stored["sections"]
    if isinstance(stored.get("language"), str):
        base["language"] = stored["language"]
    if isinstance(stored.get("custom_labels"), dict):
        base["custom_labels"] = stored["custom_labels"]
    if isinstance(stored.get("columns"), list):
        base["columns"] = stored["columns"]
    if "name" in stored: base["name"] = stored["name"]
    if "id" in stored: base["id"] = stored["id"]
    if "is_default" in stored: base["is_default"] = stored["is_default"]
    return base


async def resolve_pdf_config(db, pdf_type: str, config_id: Optional[str] = None) -> dict:
    """Load + merge config preset; falls back to type default if none."""
    cfg = None
    if config_id:
        cfg = await db.pdf_export_configs.find_one({"id": config_id})
    if not cfg:
        cfg = await db.pdf_export_configs.find_one({"pdf_type": pdf_type, "is_default": True})
    return merge_config(cfg, pdf_type)


# ─────────────────────────────────────────────────────────────────
# Section visibility helper
# ─────────────────────────────────────────────────────────────────
def is_section_on(config: dict, section_key: str) -> bool:
    enabled = config.get("sections")
    if enabled is None:
        return True   # default = on if not configured
    return section_key in enabled


# ─────────────────────────────────────────────────────────────────
# Label translator
# ─────────────────────────────────────────────────────────────────
def get_label(config: dict, key: str, fallback: Optional[str] = None) -> str:
    """Resolve label dari custom_labels → DEFAULT_LABELS → fallback string."""
    lang = (config or {}).get("language", "id")
    custom = (config or {}).get("custom_labels", {}) or {}
    if key in custom:
        v = custom[key]
        if isinstance(v, dict):
            return v.get(lang) or v.get("id") or v.get("en") or (fallback or key)
        if isinstance(v, str) and v.strip():
            return v
    if key in DEFAULT_LABELS:
        d = DEFAULT_LABELS[key]
        return d.get(lang) or d.get("id") or d.get("en") or (fallback or key)
    return fallback if fallback is not None else key


# ─────────────────────────────────────────────────────────────────
# Format helpers
# ─────────────────────────────────────────────────────────────────
def _to_int(v: Any, default: int = 0) -> int:
    try:
        return int(round(float(v or 0)))
    except (TypeError, ValueError):
        return default


def format_number(config: dict, value: Any, decimals: int = 0) -> str:
    """Group thousand separator + decimal separator per config."""
    fmt = (config or {}).get("format", {}) or {}
    grp = fmt.get("number_grouping", ".")
    dec = fmt.get("decimal_separator", ",")
    try:
        n = float(value or 0)
    except (TypeError, ValueError):
        n = 0.0
    if decimals == 0:
        s = f"{int(round(n)):,}"
        return s.replace(",", grp)
    s = f"{n:,.{decimals}f}"
    # default uses , as thousand and . as decimal — swap to user pref
    s = s.replace(",", "\x00").replace(".", dec).replace("\x00", grp)
    return s


def format_currency(config: dict, value: Any) -> str:
    sym = ((config or {}).get("format", {}) or {}).get("currency_symbol", "Rp")
    return f"{sym} {format_number(config, value, 0)}"


def format_date(config: dict, value: Any) -> str:
    """Accepts date / datetime / str (YYYY-MM-DD or ISO). Returns formatted string."""
    if value is None or value == "":
        return "-"
    if isinstance(value, datetime):
        d = value
    elif isinstance(value, date):
        d = datetime(value.year, value.month, value.day, tzinfo=timezone.utc)
    else:
        s = str(value)[:19]
        # handle YYYY-MM-DD
        try:
            d = datetime.fromisoformat(s.replace("Z", "+00:00"))
        except ValueError:
            try:
                d = datetime.strptime(s[:10], "%Y-%m-%d")
            except ValueError:
                return str(value)
    fmt = ((config or {}).get("format", {}) or {}).get("date_format", "DD/MM/YYYY")
    mapping = {
        "DD/MM/YYYY":   "%d/%m/%Y",
        "DD-MM-YYYY":   "%d-%m-%Y",
        "YYYY-MM-DD":   "%Y-%m-%d",
        "MM/DD/YYYY":   "%m/%d/%Y",
        "DD MMM YYYY":  "%d %b %Y",
        "DD MMMM YYYY": "%d %B %Y",
    }
    py_fmt = mapping.get(fmt, "%d/%m/%Y")
    try:
        return d.strftime(py_fmt)
    except (ValueError, TypeError):
        return str(value)


# ─────────────────────────────────────────────────────────────────
# Page size helper
# ─────────────────────────────────────────────────────────────────
def get_page_size(config: dict):
    """Return reportlab pagesize tuple based on config.page.size + orientation."""
    from reportlab.lib.pagesizes import A4, A5, LETTER, landscape, portrait
    page = (config or {}).get("page", {}) or {}
    size = page.get("size", "A4").upper()
    orient = page.get("orientation", "portrait").lower()
    base = {"A4": A4, "A5": A5, "LETTER": LETTER}.get(size, A4)
    return landscape(base) if orient == "landscape" else portrait(base)


def get_margins_mm(config: dict) -> tuple[float, float, float, float]:
    """Return (top, bottom, left, right) margins in mm."""
    m = ((config or {}).get("page", {}) or {}).get("margins", {}) or {}
    return (
        float(m.get("top", 18)),
        float(m.get("bottom", 16)),
        float(m.get("left", 14)),
        float(m.get("right", 14)),
    )


# ─────────────────────────────────────────────────────────────────
# Type metadata for UI consumption
# ─────────────────────────────────────────────────────────────────
def get_type_metadata(pdf_type: str, lang: str = "id") -> dict:
    """Return metadata for a PDF type (sections + customizable label keys + default labels)."""
    sections = []
    for s in PDF_SECTION_DEFINITIONS.get(pdf_type, []):
        lk = s.get("label_key", "")
        labels = DEFAULT_LABELS.get(lk, {})
        sections.append({
            "key": s["key"],
            "label_id": labels.get("id", s["key"]),
            "label_en": labels.get("en", s["key"]),
            "default_on": s.get("default_on", True),
            "required": s.get("required", False),
        })
    customizable = []
    for k in PDF_CUSTOMIZABLE_LABELS.get(pdf_type, []):
        labels = DEFAULT_LABELS.get(k, {})
        customizable.append({
            "key": k,
            "default_id": labels.get("id", k),
            "default_en": labels.get("en", k),
        })
    return {
        "pdf_type": pdf_type,
        "sections": sections,
        "customizable_labels": customizable,
        "default_config": default_config(pdf_type),
    }
